//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceWebPortal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblTechSpecFilters = new HashSet<tblTechSpecFilter>();
            this.tblTechnicalSpecifiactionNonValues = new HashSet<tblTechnicalSpecifiactionNonValue>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public short Model_Year { get; set; }
        public string Series_Info { get; set; }
        public string Accessories { get; set; }
        public int Application_ID { get; set; }
        public int Manufacturer_ID { get; set; }
        public int Mounting_ID { get; set; }
        public int Type_ID { get; set; }
        public string Image { get; set; }
        public int SubCategory_ID { get; set; }
    
        public virtual tblApplication tblApplication { get; set; }
        public virtual tblManufacturer tblManufacturer { get; set; }
        public virtual tblMountingLocation tblMountingLocation { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
        public virtual tblUseType tblUseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTechSpecFilter> tblTechSpecFilters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTechnicalSpecifiactionNonValue> tblTechnicalSpecifiactionNonValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTechnicalSpecifiactionNonValue1> tblTechnicalSpecifiactionNonValues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTechnicalSpecifiactionNonValue2> tblTechnicalSpecifiactionNonValues2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTechnicalSpecifiactionNonValue3> tblTechnicalSpecifiactionNonValues3 { get; set; }
    }
}
