//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceWebPortal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechSpecFilter
    {
        public int Filter_ID { get; set; }
        public int TechSpec_ID { get; set; }
        public double Amount { get; set; }
        public int Product_ID { get; set; }
    
        public virtual tblFilter tblFilter { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblTechSpec tblTechSpec { get; set; }
    }
}
