//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceWebPortal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_FilterTable
    {
        public string TechSpec_Name { get; set; }
        public double Amount { get; set; }
        public string Filter_Name { get; set; }
        public string SubCategory_Name { get; set; }
    }
}
